# Generated by Django 4.2.1 on 2023-06-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manancial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mananciais',
            name='capacidade',
            field=models.PositiveIntegerField(verbose_name='Capacidade'),
        ),
    ]
