# Generated by Django 4.2.1 on 2023-06-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_municipios_alter_estados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios',
            options={'ordering': ['nome'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
