# Generated by Django 4.2.1 on 2023-06-12 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_estados_atualizado_em_estados_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
