# Generated by Django 4.2.1 on 2023-06-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_lotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.lotes', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nome'],
            },
        ),
    ]
