# Generated by Django 4.2.1 on 2023-06-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manancial', '0002_alter_mananciais_capacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnh', models.CharField(max_length=50, verbose_name='CNH')),
                ('foto_pipeiro', models.ImageField(upload_to='pipeiros', verbose_name='Foto Pipeiro')),
                ('celular', models.CharField(max_length=14, verbose_name='Celular')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa')),
                ('foto_veiculo', models.ImageField(upload_to='veiculos', verbose_name='Foto Veículo')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('S', 'Suspenso')], default='I', max_length=1, verbose_name='Status')),
                ('manancial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manancial.mananciais', verbose_name='Mananciais')),
            ],
            options={
                'verbose_name': 'Pipeiro',
                'verbose_name_plural': 'Pipeiros',
                'ordering': ['nome', 'placa'],
            },
        ),
    ]
